name: Install and Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-linux:
    defaults:
      run:
        # Ensures environment gets sourced right
        shell: bash -l -e {0}
    name: Python (${{ matrix.PYTHON_VERSION }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: ["3.10", "3.11", "3.12"]
    env:
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    steps:
    - uses: actions/checkout@v4

    - name: Add /etc/hosts entries
      run: |
        cat .github/workflows/etchosts.txt | sudo tee -a /etc/hosts

    - name: Run IEM Database container
      run: |
        docker run -d --name iem_database -p 5432:5432 ghcr.io/akrherz/iem_database:test_data
        until docker exec iem_database pg_isready -h localhost; do
          sleep 6
        done

    - name: Copy default settings.json
      run: |
        cp settings.json-in settings.json

    # setup conda-forge with micromamba
    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        condarc: |
          channels:
            - conda-forge
            - defaults
        create-args: >-
          python=${{ env.PYTHON_VERSION }}
        environment-name: prod
        cache-environment: true

    - name: Build and Test
      run: |
        python -m pip install . --upgrade
        python -m coverage run --source=pyvbcam -m pytest
        python -m coverage xml

    - name: Code coverage
      if: ${{ matrix.PYTHON_VERSION == '3.12' }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
