name: Install and Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-linux:
    defaults:
      run:
        # Ensures environment gets sourced right
        shell: bash -l {0}
    name: Python (${{ matrix.PYTHON_VERSION }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 3.12 disabled for now as posix_ipc is not available in cf
        PYTHON_VERSION: ["3.9", "3.11"]
    env:
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    steps:
    - uses: actions/checkout@v4

    - name: Add /etc/hosts entries
      run: |
        cat .github/workflows/etchosts.txt | sudo tee -a /etc/hosts

    - name: Copy default settings.json
      run: |
        cp settings.json-in settings.json

    # setup conda-forge with micromamba
    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        condarc: |
          channels:
            - conda-forge
            - defaults
        create-args: >-
          python=${{ env.PYTHON_VERSION }}
        environment-name: prod
        cache-environment: true

    - name: Setup Postgres
      run: |
        git clone --depth 1 https://github.com/akrherz/iem-database.git database
        git clone --depth 1 https://github.com/akrherz/ci_tooling.git .ci_tooling
        cd .ci_tooling
        . postgres.sh
        cd ..
        cd database; sh bootstrap.sh
        python schema_manager.py
        python store_test_data.py

    - name: Build and Test
      run: |
        # Ensure we exit on any failure
        set -e
        python -m pip install . --upgrade
        python -m coverage run --source=pyvbcam -m pytest
        python -m coverage xml

    - name: Code coverage
      if: ${{ matrix.PYTHON_VERSION == '3.12' }}
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
