name: Install and Test
on: [push]
jobs:
  build-linux:
    name: Python (${{ matrix.PYTHON_VERSION }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: ["3.9", "3.10", "3.11"]
    env:
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup CI from ci-tooling
      run: |
        git clone --depth 1 https://github.com/akrherz/ci_tooling.git .ci_tooling
        . .ci_tooling/miniconda.sh
        pip install codecov
        python -m pip install . --upgrade
        echo '{}' > settings.json
        coverage run --source=pyvbcam setup.py test
        if [[ ${{ matrix.PYTHON_VERSION }} == "3.11" ]]; then
          codecov
        fi
